version: '3'
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80" # HTTP
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  neo4j:
    image: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - "./graph_data:/data"
      - "./import:/import"
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=none
      - NEO4J_server_memory_heap_initial__size=6G
      - NEO4J_server_memory_heap_max__size=16G
      - NEO4J_server_memory_pagecache_size=4G


  apeman-frontend:
    build:
      context: ui/apeman-ui
      dockerfile: Dockerfile
    image: apeman-frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.apeman-frontend.rule=Host(`apeman-frontend.localhost`)
      - traefik.http.routers.apeman-frontend.service=apeman-frontend
      - traefik.http.services.apeman-frontend.loadbalancer.server.port=80

  apeman-backend:
    build:
      context: ./cmd
      dockerfile: Dockerfile
    image: apeman-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.apeman-backend.rule=Host(`apeman-backend.localhost`)
      - traefik.http.routers.apeman-backend.service=apeman-backend
      - traefik.http.services.apeman-backend.loadbalancer.server.port=4400


